### ISSUE TITLE
This repository: Is its publication intended?

### ISSUE THREAD

**Issue by peteroupc** [LoudCloud9/GoogleBot#210]
#### Brief description of the issue:
I just stumbled upon this repository, and it appears to be an enterprise application of a kind which is normally not seen as a publicly available repository.  Was this application's publication here intended, so that any GitHub user can contribute?  This is not clear from the README.

**Comment by SpadesNeil** [comment]
It won't actually work without a number of things kept privately. That said, I should probably stick a proper set of licensing information on this. Thanks for the heads up.

**Comment by SpadesNeil** [comment]
Didn't mean to close this...

**Comment by MTS11648** [comment]
Just out of curiosity, how did you find this repository anyway? A keyword you searched or..?

**Comment by peteroupc** [comment]
@MTS11648:

Yes.  It appeared in the search results for GitHub issues when I was searching for something else.

**Comment by SpadesNeil** [comment]
This will soon (finally) be moved into a private repository. Closing this now.
